### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Suspicious-Goat** [brhaka/sfml-compiler#1]
After I hit F9, it creates the build folder, but it is empty. I read the error log, and it said:

> C:\Users\--\Desktop\stuff\cpp\main.cpp: In function 'int main()':
> C:\Users\--\Desktop\stuff\cpp\main.cpp:2:5: error: 'sf' has not been declared
>      sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");
>      ^~
> C:\Users\--\Desktop\stuff\cpp\main.cpp:3:5: error: 'sf' has not been declared
>      sf::CircleShape shape(100.f);
>      ^~
> C:\Users\--\Desktop\stuff\cpp\main.cpp:4:5: error: 'shape' was not declared in this scope
>      shape.setFillColor(sf::Color::Green);
>      ^~~~~
> C:\Users\--\Desktop\stuff\cpp\main.cpp:4:24: error: 'sf' has not been declared
>      shape.setFillColor(sf::Color::Green);
>                         ^~
> C:\Users\--\Desktop\stuff\cpp\main.cpp:6:12: error: 'window' was not declared in this scope
>      while (window.isOpen())
>             ^~~~~~
> C:\Users\--\Desktop\stuff\cpp\main.cpp:8:9: error: 'sf' has not been declared
>          sf::Event event;
>          ^~
> C:\Users\--\Desktop\stuff\cpp\main.cpp:9:33: error: 'event' was not declared in this scope
>          while (window.pollEvent(event))
>                                  ^~~~~
> C:\Users\--\Desktop\stuff\cpp\main.cpp:11:31: error: 'sf' has not been declared
>              if (event.type == sf::Event::Closed)
>                                ^~

Here are my settings. 

![Capture](https://user-images.githubusercontent.com/51968364/59780516-1fe7c000-9288-11e9-85a2-009921cecdb1.JPG)

**Comment by brhaka** [comment]
You must include SFML specific classes, like `#include <SFML/Graphics.hpp>`, or any class that your code needs.
